# Generated by Django 2.2.24 on 2024-05-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20240529_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Новостройка'),
        ),
    ]
