# Generated by Django 2.2.24 on 2024-05-29 07:46

from django.db import migrations


def new_bilding(apps, shema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year and flat.construction_year >= 2015:
            flat.new_building = True
        else:
            flat.new_building = False
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20240529_1036'),
    ]

    operations = [
        migrations.RunPython(new_bilding)
    ]
