# Generated by Django 2.2.24 on 2024-05-29 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0007_сomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='Лайки', to=settings.AUTH_USER_MODEL),
        ),
    ]
