# Generated by Django 2.2.24 on 2024-05-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20240529_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owners',
        ),
        migrations.AddField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(blank=True, related_name='owners', to='property.Flat'),
        ),
    ]
