# Generated by Django 2.2.24 on 2024-05-29 10:03

from django.db import migrations
from ..models import Flat, Owner


def migrate_flat_owners(apps, schema_editor):
    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(
            full_name=flat.owner,
            phone_nuber=flat.owners_phonenumber,
            pure_phone_number=flat.owner_pure_phone
        )
        flat.owners.add(owner)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20240529_1258'),
    ]

    operations = [
        migrations.RunPython(migrate_flat_owners)
    ]
