# Generated by Django 2.2.24 on 2024-05-31 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_owner_migrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
