# Generated by Django 2.2.24 on 2024-05-31 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0017_auto_20240531_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='liked',
        ),
        migrations.AddField(
            model_name='flat',
            name='liked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liked_flats', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
